project_id = "ixtwbkikyuexskdgfpfq"

[functions.test-ping]
verify_jwt = false

[functions.send-sms-alert]
verify_jwt = false

[functions.exchange-fitbase-token]
verify_jwt = false

[functions.fetch-fitbit-data]
verify_jwt = false

[functions.calc-trends]
verify_jwt = false

[functions.calculate-baseline]
verify_jwt = false

[functions.calculate-deviation]
verify_jwt = false

[functions.fetch-fitbit-auto]
verify_jwt = false
