import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const EFFECTIVE_DATE = "8 March 2026";
const COMPANY = "Predictiv";
const CONTACT_EMAIL = "justin15muller@gmail.com";

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-white text-slate-800">
      {/* Nav bar */}
      <nav className="sticky top-0 bg-white/90 backdrop-blur border-b border-slate-100 z-10">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center gap-3">
          <button
            onClick={() => navigate(-1)}
            className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-500 transition-colors"
            aria-label="Go back"
          >
            <ArrowLeft className="h-4 w-4" />
          </button>
          <span className="text-sm font-medium text-slate-600">Terms of Service</span>
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-4 py-10 pb-20 prose prose-slate prose-sm sm:prose-base max-w-none">
        <h1 className="text-2xl sm:text-3xl font-bold text-slate-900 mb-1">{COMPANY} Terms of Service</h1>
        <p className="text-sm text-slate-400 mb-8">Effective date: {EFFECTIVE_DATE}</p>

        <Section title="1. About Predictiv">
          <p>
            {COMPANY} is a digital sports-performance and personal-health tracking application ("<strong>the Service</strong>") that aggregates data from wearable devices, provides AI-generated insights, and connects users with healthcare and fitness professionals. The Service is operated from the Republic of South Africa.
          </p>
          <p>
            By creating an account or using the Service you agree to be bound by these Terms. If you do not agree, do not use the Service.
          </p>
        </Section>

        <Section title="2. Who the Service is for">
          <p>
            The Service is intended for individuals aged 18 and older who wish to monitor their own health and athletic performance. Users under 18 may only use the Service with the express consent of a parent or legal guardian, who accepts these Terms on their behalf.
          </p>
          <p>
            Practitioner accounts are available to qualified healthcare and fitness professionals who have been approved by {COMPANY}. Approval does not constitute endorsement of a practitioner's qualifications or services.
          </p>
        </Section>

        <Section title="3. Your account">
          <p>
            You are responsible for maintaining the security of your account credentials. You must not share your password or allow others to access your account. You agree to notify us immediately at <a href={`mailto:${CONTACT_EMAIL}`} className="text-blue-600 hover:underline">{CONTACT_EMAIL}</a> if you suspect unauthorised access.
          </p>
          <p>
            You are responsible for all activity that occurs under your account, whether or not authorised by you.
          </p>
        </Section>

        <Section title="4. User responsibilities">
          <p>You agree that you will not:</p>
          <ul>
            <li>Use the Service for any unlawful purpose or in violation of any applicable law;</li>
            <li>Attempt to reverse-engineer, decompile, or extract source code from any part of the Service;</li>
            <li>Scrape, harvest, or systematically collect data from the Service;</li>
            <li>Upload or transmit viruses, malware, or other harmful code;</li>
            <li>Impersonate another person or misrepresent your affiliation with any person or entity;</li>
            <li>Use the Service in any way that could damage, overburden, or impair its infrastructure.</li>
          </ul>
        </Section>

        <Section title="5. Health data disclaimer — not medical advice">
          <p className="font-semibold text-slate-900">
            Predictiv is not a medical device and does not provide medical advice, diagnosis, or treatment.
          </p>
          <p>
            All content generated by the Service — including AI-generated insights, daily briefings, recommendations, risk scores, and anomaly alerts — is provided for informational and educational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment from a qualified healthcare provider.
          </p>
          <p>
            Always seek the advice of your physician or another qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay seeking it because of something you have read on or through the Service.
          </p>
          <p>
            In the event of a medical emergency, call <strong>10177</strong> (emergency medical services, South Africa) or go immediately to your nearest emergency room.
          </p>
          <p>
            The accuracy of insights depends on the quality and completeness of data supplied by your wearable devices and the information you provide. {COMPANY} makes no warranty that data will be accurate, complete, or timely.
          </p>
        </Section>

        <Section title="6. Wearable device and third-party integrations">
          <p>
            The Service integrates with third-party wearable platforms (including Oura, Garmin, and Polar). By connecting a device you authorise {COMPANY} to retrieve data from that platform on your behalf. You remain subject to each platform's own terms of service and privacy policy. {COMPANY} is not responsible for the accuracy, availability, or conduct of any third-party platform.
          </p>
        </Section>

        <Section title="7. Intellectual property">
          <p>
            All software, content, and materials comprising the Service are the property of {COMPANY} or its licensors and are protected by South African and international intellectual property laws. You are granted a limited, non-exclusive, non-transferable licence to use the Service for personal, non-commercial purposes only.
          </p>
          <p>
            Data you submit to the Service (e.g., health notes, goals, and documents) remains yours. You grant {COMPANY} a limited licence to process that data solely for the purpose of providing the Service to you.
          </p>
        </Section>

        <Section title="8. Limitation of liability">
          <p>
            To the fullest extent permitted by applicable law, {COMPANY} and its directors, employees, and agents are not liable for any indirect, incidental, special, consequential, or punitive damages arising out of or relating to your use of, or inability to use, the Service — including any reliance on AI-generated health insights.
          </p>
          <p>
            Nothing in these Terms limits liability for death or personal injury caused by negligence, or for fraud or fraudulent misrepresentation.
          </p>
        </Section>

        <Section title="9. Account termination">
          <p>
            You may delete your account at any time by contacting us at <a href={`mailto:${CONTACT_EMAIL}`} className="text-blue-600 hover:underline">{CONTACT_EMAIL}</a>. Upon deletion, your personal data will be handled in accordance with our <a href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</a>.
          </p>
          <p>
            {COMPANY} reserves the right to suspend or terminate your account, with or without notice, if you breach these Terms or if we are required to do so by law.
          </p>
        </Section>

        <Section title="10. Changes to these Terms">
          <p>
            We may update these Terms from time to time. Material changes will be communicated by email or in-app notification at least 14 days before they take effect. Your continued use of the Service after that date constitutes acceptance of the revised Terms.
          </p>
        </Section>

        <Section title="11. Governing law and jurisdiction">
          <p>
            These Terms are governed by the laws of the Republic of South Africa. Any dispute arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of South Africa.
          </p>
          <p>
            If you are a consumer, nothing in this clause affects your rights under applicable South African consumer protection legislation, including the Consumer Protection Act 68 of 2008.
          </p>
        </Section>

        <Section title="12. Contact">
          <p>
            Questions about these Terms should be sent to{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-blue-600 hover:underline">{CONTACT_EMAIL}</a>.
          </p>
        </Section>

        {/* Footer */}
        <div className="mt-12 pt-6 border-t border-slate-100 flex flex-wrap gap-4 text-xs text-slate-400">
          <a href="/privacy" className="hover:text-slate-600 underline">Privacy Policy</a>
          <a href="/" className="hover:text-slate-600">← Back to Predictiv</a>
        </div>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-lg font-semibold text-slate-900 mb-3">{title}</h2>
      <div className="space-y-3 text-slate-600 leading-relaxed text-sm sm:text-base">
        {children}
      </div>
    </section>
  );
}
