SET check_function_bodies = false;
ALTER TABLE public."Bookings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Users" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_rows_select" ON public."Users" FOR SELECT TO authenticated USING (auth.uid() = "id");
CREATE POLICY "own_rows_insert" ON public."Users" FOR INSERT TO authenticated WITH CHECK (auth.uid() = "id");
CREATE POLICY "own_rows_update" ON public."Users" FOR UPDATE TO authenticated USING (auth.uid() = "id") WITH CHECK (auth.uid() = "id");
CREATE POLICY "own_rows_delete" ON public."Users" FOR DELETE TO authenticated USING (auth.uid() = "id");
ALTER TABLE public."Wearables" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_rows_select" ON public."Wearables" FOR SELECT TO authenticated USING (auth.uid() = "user_id");
CREATE POLICY "own_rows_insert" ON public."Wearables" FOR INSERT TO authenticated WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_update" ON public."Wearables" FOR UPDATE TO authenticated USING (auth.uid() = "user_id") WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_delete" ON public."Wearables" FOR DELETE TO authenticated USING (auth.uid() = "user_id");
CREATE POLICY "own_rows_select" ON public."garmin_oauth_state" FOR SELECT TO authenticated USING (auth.uid() = "user_id");
CREATE POLICY "own_rows_insert" ON public."garmin_oauth_state" FOR INSERT TO authenticated WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_update" ON public."garmin_oauth_state" FOR UPDATE TO authenticated USING (auth.uid() = "user_id") WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_delete" ON public."garmin_oauth_state" FOR DELETE TO authenticated USING (auth.uid() = "user_id");
ALTER TABLE public."health_daily" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_rows_select" ON public."health_daily" FOR SELECT TO authenticated USING (auth.uid() = "user_id");
CREATE POLICY "own_rows_insert" ON public."health_daily" FOR INSERT TO authenticated WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_update" ON public."health_daily" FOR UPDATE TO authenticated USING (auth.uid() = "user_id") WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_delete" ON public."health_daily" FOR DELETE TO authenticated USING (auth.uid() = "user_id");
ALTER TABLE public."health_data" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_rows_select" ON public."health_data" FOR SELECT TO authenticated USING (auth.uid() = "user_id");
CREATE POLICY "own_rows_insert" ON public."health_data" FOR INSERT TO authenticated WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_update" ON public."health_data" FOR UPDATE TO authenticated USING (auth.uid() = "user_id") WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_delete" ON public."health_data" FOR DELETE TO authenticated USING (auth.uid() = "user_id");
ALTER TABLE public."oura_sync_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."plan_adherence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."polar_webhooks" ENABLE ROW LEVEL SECURITY;
-- polar_webhooks: no user column; service_role only
ALTER TABLE public."training_trends" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_rows_select" ON public."training_trends" FOR SELECT TO authenticated USING (auth.uid() = "user_id");
CREATE POLICY "own_rows_insert" ON public."training_trends" FOR INSERT TO authenticated WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_update" ON public."training_trends" FOR UPDATE TO authenticated USING (auth.uid() = "user_id") WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_delete" ON public."training_trends" FOR DELETE TO authenticated USING (auth.uid() = "user_id");
ALTER TABLE public."user_baselines" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."yves_feedback" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "own_rows_select" ON public."yves_feedback" FOR SELECT TO authenticated USING (auth.uid() = "user_id");
CREATE POLICY "own_rows_insert" ON public."yves_feedback" FOR INSERT TO authenticated WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_update" ON public."yves_feedback" FOR UPDATE TO authenticated USING (auth.uid() = "user_id") WITH CHECK (auth.uid() = "user_id");
CREATE POLICY "own_rows_delete" ON public."yves_feedback" FOR DELETE TO authenticated USING (auth.uid() = "user_id");
ALTER TABLE public."yves_profiles" ENABLE ROW LEVEL SECURITY;
