SET check_function_bodies = false;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."Bookings" TO authenticated;
GRANT ALL ON public."Bookings" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."Users" TO authenticated;
GRANT ALL ON public."Users" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."Wearables" TO authenticated;
GRANT ALL ON public."Wearables" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."accountability_challenges" TO authenticated;
GRANT ALL ON public."accountability_challenges" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."activity_trends" TO authenticated;
GRANT ALL ON public."activity_trends" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."adaptive_recommendations" TO authenticated;
GRANT ALL ON public."adaptive_recommendations" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."alert_history" TO authenticated;
GRANT ALL ON public."alert_history" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."alert_settings" TO authenticated;
GRANT ALL ON public."alert_settings" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."baseline_profiles" TO authenticated;
GRANT ALL ON public."baseline_profiles" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."csv_uploads" TO authenticated;
GRANT ALL ON public."csv_uploads" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."daily_briefings" TO authenticated;
GRANT ALL ON public."daily_briefings" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."document_insights" TO authenticated;
GRANT ALL ON public."document_insights" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."document_processing_log" TO authenticated;
GRANT ALL ON public."document_processing_log" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."document_versions" TO authenticated;
GRANT ALL ON public."document_versions" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."engagement_events" TO authenticated;
GRANT ALL ON public."engagement_events" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."escalation_log" TO authenticated;
GRANT ALL ON public."escalation_log" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."escalation_rules" TO authenticated;
GRANT ALL ON public."escalation_rules" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."feedback" TO authenticated;
GRANT ALL ON public."feedback" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."feedback_summary" TO authenticated;
GRANT ALL ON public."feedback_summary" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."fitbit_auto_data" TO authenticated;
GRANT ALL ON public."fitbit_auto_data" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."fitbit_tokens" TO authenticated;
GRANT ALL ON public."fitbit_tokens" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."fitbit_trends" TO authenticated;
GRANT ALL ON public."fitbit_trends" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."function_execution_log" TO authenticated;
GRANT ALL ON public."function_execution_log" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."garmin_oauth_state" TO authenticated;
GRANT ALL ON public."garmin_oauth_state" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."google_calendar_events" TO authenticated;
GRANT ALL ON public."google_calendar_events" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."google_calendar_sync_logs" TO authenticated;
GRANT ALL ON public."google_calendar_sync_logs" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."google_calendar_tokens" TO authenticated;
GRANT ALL ON public."google_calendar_tokens" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."health_anomalies" TO authenticated;
GRANT ALL ON public."health_anomalies" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."health_daily" TO authenticated;
GRANT ALL ON public."health_daily" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."health_data" TO authenticated;
GRANT ALL ON public."health_data" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."health_trends_daily" TO authenticated;
GRANT ALL ON public."health_trends_daily" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."health_trends_weekly" TO authenticated;
GRANT ALL ON public."health_trends_weekly" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."healthcare_practitioners" TO authenticated;
GRANT ALL ON public."healthcare_practitioners" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."insight_engagement_summary" TO authenticated;
GRANT ALL ON public."insight_engagement_summary" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."insight_feedback" TO authenticated;
GRANT ALL ON public."insight_feedback" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."insight_history" TO authenticated;
GRANT ALL ON public."insight_history" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."medical_finder_sessions" TO authenticated;
GRANT ALL ON public."medical_finder_sessions" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."notification_log" TO authenticated;
GRANT ALL ON public."notification_log" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."onboarding_signals" TO authenticated;
GRANT ALL ON public."onboarding_signals" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_activity" TO authenticated;
GRANT ALL ON public."oura_activity" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_cardiovascular_age" TO authenticated;
GRANT ALL ON public."oura_cardiovascular_age" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_logs" TO authenticated;
GRANT ALL ON public."oura_logs" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_readiness" TO authenticated;
GRANT ALL ON public."oura_readiness" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_resilience" TO authenticated;
GRANT ALL ON public."oura_resilience" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_rest_mode" TO authenticated;
GRANT ALL ON public."oura_rest_mode" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_ring_config" TO authenticated;
GRANT ALL ON public."oura_ring_config" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_sleep" TO authenticated;
GRANT ALL ON public."oura_sleep" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_spo2" TO authenticated;
GRANT ALL ON public."oura_spo2" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_stress" TO authenticated;
GRANT ALL ON public."oura_stress" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_sync_log" TO authenticated;
GRANT ALL ON public."oura_sync_log" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_tokens" TO authenticated;
GRANT ALL ON public."oura_tokens" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_vo2max" TO authenticated;
GRANT ALL ON public."oura_vo2max" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."oura_workout" TO authenticated;
GRANT ALL ON public."oura_workout" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."physicians" TO authenticated;
GRANT ALL ON public."physicians" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."plan_adherence" TO authenticated;
GRANT ALL ON public."plan_adherence" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."polar_logs" TO authenticated;
GRANT ALL ON public."polar_logs" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."polar_tokens" TO authenticated;
GRANT ALL ON public."polar_tokens" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."polar_webhooks" TO authenticated;
GRANT ALL ON public."polar_webhooks" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."practitioner_access" TO authenticated;
GRANT ALL ON public."practitioner_access" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."practitioner_bookings" TO authenticated;
GRANT ALL ON public."practitioner_bookings" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."practitioner_specialties" TO authenticated;
GRANT ALL ON public."practitioner_specialties" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."practitioners" TO authenticated;
GRANT ALL ON public."practitioners" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."prediction_log" TO authenticated;
GRANT ALL ON public."prediction_log" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."profiles" TO authenticated;
GRANT ALL ON public."profiles" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."prompt_history" TO authenticated;
GRANT ALL ON public."prompt_history" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."provider_reviews" TO authenticated;
GRANT ALL ON public."provider_reviews" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."rate_limit_state" TO authenticated;
GRANT ALL ON public."rate_limit_state" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."rate_limits" TO authenticated;
GRANT ALL ON public."rate_limits" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."recommendation_outcomes" TO authenticated;
GRANT ALL ON public."recommendation_outcomes" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."recovery_trends" TO authenticated;
GRANT ALL ON public."recovery_trends" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."review_helpful_votes" TO authenticated;
GRANT ALL ON public."review_helpful_votes" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."risk_alert_dismissals" TO authenticated;
GRANT ALL ON public."risk_alert_dismissals" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."risk_score_history" TO authenticated;
GRANT ALL ON public."risk_score_history" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."risk_trajectories" TO authenticated;
GRANT ALL ON public."risk_trajectories" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."service_categories" TO authenticated;
GRANT ALL ON public."service_categories" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."symptom_check_ins" TO authenticated;
GRANT ALL ON public."symptom_check_ins" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."sync_health_log" TO authenticated;
GRANT ALL ON public."sync_health_log" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."sync_retry_queue" TO authenticated;
GRANT ALL ON public."sync_retry_queue" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."terra_connections" TO authenticated;
GRANT ALL ON public."terra_connections" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."training_trends" TO authenticated;
GRANT ALL ON public."training_trends" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."treatment_plan_feedback" TO authenticated;
GRANT ALL ON public."treatment_plan_feedback" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."treatment_plan_services" TO authenticated;
GRANT ALL ON public."treatment_plan_services" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."treatment_plans" TO authenticated;
GRANT ALL ON public."treatment_plans" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."triage_results" TO authenticated;
GRANT ALL ON public."triage_results" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_adaptation_profile" TO authenticated;
GRANT ALL ON public."user_adaptation_profile" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_baselines" TO authenticated;
GRANT ALL ON public."user_baselines" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_challenges" TO authenticated;
GRANT ALL ON public."user_challenges" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_context" TO authenticated;
GRANT ALL ON public."user_context" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_context_enhanced" TO authenticated;
GRANT ALL ON public."user_context_enhanced" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_data_maturity" TO authenticated;
GRANT ALL ON public."user_data_maturity" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_deviations" TO authenticated;
GRANT ALL ON public."user_deviations" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_documents" TO authenticated;
GRANT ALL ON public."user_documents" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_focus_preferences" TO authenticated;
GRANT ALL ON public."user_focus_preferences" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_health_profiles" TO authenticated;
GRANT ALL ON public."user_health_profiles" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_injuries" TO authenticated;
GRANT ALL ON public."user_injuries" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_injury_profiles" TO authenticated;
GRANT ALL ON public."user_injury_profiles" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_insight_actions" TO authenticated;
GRANT ALL ON public."user_insight_actions" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_insights_view" TO authenticated;
GRANT ALL ON public."user_insights_view" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_interests" TO authenticated;
GRANT ALL ON public."user_interests" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_life_formula" TO authenticated;
GRANT ALL ON public."user_life_formula" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_lifestyle" TO authenticated;
GRANT ALL ON public."user_lifestyle" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_medical" TO authenticated;
GRANT ALL ON public."user_medical" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_mindset" TO authenticated;
GRANT ALL ON public."user_mindset" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_model" TO authenticated;
GRANT ALL ON public."user_model" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_nutrition" TO authenticated;
GRANT ALL ON public."user_nutrition" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_profile" TO authenticated;
GRANT ALL ON public."user_profile" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_profiles" TO authenticated;
GRANT ALL ON public."user_profiles" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_recovery" TO authenticated;
GRANT ALL ON public."user_recovery" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_roles" TO authenticated;
GRANT ALL ON public."user_roles" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_shown_patterns" TO authenticated;
GRANT ALL ON public."user_shown_patterns" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_training" TO authenticated;
GRANT ALL ON public."user_training" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_treatment_preferences" TO authenticated;
GRANT ALL ON public."user_treatment_preferences" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."user_wellness_goals" TO authenticated;
GRANT ALL ON public."user_wellness_goals" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."users" TO authenticated;
GRANT ALL ON public."users" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."wearable_auto_data" TO authenticated;
GRANT ALL ON public."wearable_auto_data" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."wearable_sessions" TO authenticated;
GRANT ALL ON public."wearable_sessions" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."wearable_summary" TO authenticated;
GRANT ALL ON public."wearable_summary" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."wearable_tokens" TO authenticated;
GRANT ALL ON public."wearable_tokens" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."weekly_reflections" TO authenticated;
GRANT ALL ON public."weekly_reflections" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."yves_feedback" TO authenticated;
GRANT ALL ON public."yves_feedback" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."yves_memory_bank" TO authenticated;
GRANT ALL ON public."yves_memory_bank" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."yves_profiles" TO authenticated;
GRANT ALL ON public."yves_profiles" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."yves_recommendations" TO authenticated;
GRANT ALL ON public."yves_recommendations" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."yves_timeline_view" TO authenticated;
GRANT ALL ON public."yves_timeline_view" TO service_role;
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
