SET check_function_bodies = false;
CREATE POLICY "Users can view their own terra connections" ON public.terra_connections FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own training preferences" ON public.user_training FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own triage results" ON public.triage_results FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own uploads" ON public.csv_uploads FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own wearable sessions" ON public.wearable_sessions FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own wearable summary" ON public.wearable_summary FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own weekly trends" ON public.health_trends_weekly FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own wellness goals" ON public.user_wellness_goals FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own yves profile" ON public.yves_profiles FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own yves recommendations" ON public.yves_recommendations FOR SELECT TO authenticated USING ((auth.uid() = user_id));
ALTER TABLE public.accountability_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_trends ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.adaptive_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.baseline_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.csv_uploads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_briefings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_processing_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.engagement_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.escalation_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.escalation_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fitbit_auto_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fitbit_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fitbit_trends ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.function_execution_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.garmin_oauth_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.google_calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.google_calendar_sync_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.google_calendar_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_anomalies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_trends_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_trends_weekly ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.healthcare_practitioners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insight_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insight_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_finder_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_cardiovascular_age ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_readiness ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_resilience ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_rest_mode ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_ring_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_sleep ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_spo2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_stress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_vo2max ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oura_workout ENABLE ROW LEVEL SECURITY;
CREATE POLICY patients_insert_grants ON public.practitioner_access FOR INSERT WITH CHECK ((patient_id = auth.uid()));
CREATE POLICY patients_read_own_grants ON public.practitioner_access FOR SELECT USING ((patient_id = auth.uid()));
CREATE POLICY patients_update_own_grants ON public.practitioner_access FOR UPDATE USING ((patient_id = auth.uid()));
ALTER TABLE public.physicians ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.polar_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.polar_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.practitioner_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.practitioner_bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY practitioner_read_patient_injury_profiles ON public.user_injury_profiles FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.practitioner_access pa
  WHERE ((pa.practitioner_id = auth.uid()) AND (pa.patient_id = user_injury_profiles.user_id) AND (pa.is_active = true)))));
CREATE POLICY practitioner_read_patient_wearable_sessions ON public.wearable_sessions FOR SELECT USING ((EXISTS ( SELECT 1
   FROM public.practitioner_access pa
  WHERE ((pa.practitioner_id = auth.uid()) AND (pa.patient_id = wearable_sessions.user_id) AND (pa.is_active = true)))));
ALTER TABLE public.practitioner_specialties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.practitioners ENABLE ROW LEVEL SECURITY;
CREATE POLICY practitioners_read_own_access ON public.practitioner_access FOR SELECT USING ((practitioner_id = auth.uid()));
ALTER TABLE public.prediction_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompt_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rate_limit_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendation_outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recovery_trends ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_helpful_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risk_alert_dismissals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risk_score_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risk_trajectories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.symptom_check_ins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_health_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_retry_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.terra_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatment_plan_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatment_plan_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatment_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.triage_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_adaptation_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_context ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_context_enhanced ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_data_maturity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_deviations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_focus_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_health_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_injuries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_injury_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_insight_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_life_formula ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_lifestyle ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_medical ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_mindset ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_model ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_nutrition ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_recovery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_shown_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_training ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_treatment_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_wellness_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_manage_own_risk_scores ON public.risk_score_history USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
ALTER TABLE public.wearable_auto_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wearable_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wearable_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wearable_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_reflections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.yves_memory_bank ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.yves_recommendations ENABLE ROW LEVEL SECURITY;
