SET check_function_bodies = false;
CREATE POLICY "Users can insert own insights" ON public.insight_history FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert own pattern views" ON public.user_shown_patterns FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert own polar logs" ON public.polar_logs FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert own polar tokens" ON public.polar_tokens FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert own profile" ON public.user_profiles FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert own readiness data" ON public.oura_readiness FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can insert own record" ON public.users FOR INSERT WITH CHECK ((auth.uid() = id));
CREATE POLICY "Users can insert own resilience data" ON public.oura_resilience FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can insert own rest mode data" ON public.oura_rest_mode FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can insert own ring config" ON public.oura_ring_config FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can insert own sleep data" ON public.oura_sleep FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can insert own spo2 data" ON public.oura_spo2 FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can insert own stress data" ON public.oura_stress FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can insert own sync logs" ON public.google_calendar_sync_logs FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert own vo2max data" ON public.oura_vo2max FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can insert own workout data" ON public.oura_workout FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can insert their own Fitbit tokens" ON public.fitbit_tokens FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own Fitbit tokens" ON public.wearable_tokens FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own alert history" ON public.alert_history FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own alert settings" ON public.alert_settings FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own baselines" ON public.user_baselines FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own context" ON public.user_context_enhanced FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own dismissals" ON public.risk_alert_dismissals FOR INSERT WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own documents" ON public.user_documents FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own feedback" ON public.feedback FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own injury history" ON public.user_injuries FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own insight actions" ON public.user_insight_actions FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own insight feedback" ON public.insight_feedback FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own insight history" ON public.insight_history FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own interests" ON public.user_interests FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own lifestyle" ON public.user_lifestyle FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own medical background" ON public.user_medical FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own memory entries" ON public.yves_memory_bank FOR INSERT WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own mindset data" ON public.user_mindset FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own nutrition" ON public.user_nutrition FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK ((auth.uid() = id));
CREATE POLICY "Users can insert their own profile" ON public.user_profile FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own recovery data" ON public.user_recovery FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own sessions" ON public.medical_finder_sessions FOR INSERT WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own signals" ON public.onboarding_signals FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own terra connections" ON public.terra_connections FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own training preferences" ON public.user_training FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own triage results" ON public.triage_results FOR INSERT WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own uploads" ON public.csv_uploads FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own wearable sessions" ON public.wearable_sessions FOR INSERT WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own wearable summary" ON public.wearable_summary FOR INSERT WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own wellness goals" ON public.user_wellness_goals FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can read own focus preferences" ON public.user_focus_preferences FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can read own polar logs" ON public.polar_logs FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can read own polar tokens" ON public.polar_tokens FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can read own record" ON public.users FOR SELECT TO authenticated USING ((auth.uid() = id));
CREATE POLICY "Users can read their own baselines" ON public.user_baselines FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can read their own layout preferences" ON public.profiles FOR SELECT USING ((auth.uid() = id));
CREATE POLICY "Users can remove helpful votes" ON public.review_helpful_votes FOR DELETE TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can update active field only" ON public.user_model FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update outcome on their own predictions" ON public.prediction_log FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own activity data" ON public.oura_activity FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update own calendar events" ON public.google_calendar_events FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own calendar tokens" ON public.google_calendar_tokens FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own cardiovascular age data" ON public.oura_cardiovascular_age FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update own challenges" ON public.accountability_challenges FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own challenges" ON public.user_challenges FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own context" ON public.user_context FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own focus preferences" ON public.user_focus_preferences FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own injury profiles" ON public.user_injury_profiles FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own polar tokens" ON public.polar_tokens FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own profile" ON public.user_profiles FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own readiness data" ON public.oura_readiness FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update own record" ON public.users FOR UPDATE TO authenticated USING ((auth.uid() = id));
CREATE POLICY "Users can update own reflections" ON public.weekly_reflections FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own resilience data" ON public.oura_resilience FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update own rest mode data" ON public.oura_rest_mode FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update own ring config" ON public.oura_ring_config FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update own sleep data" ON public.oura_sleep FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update own spo2 data" ON public.oura_spo2 FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update own stress data" ON public.oura_stress FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update own treatment plans" ON public.treatment_plans FOR UPDATE TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can update own treatment preferences" ON public.user_treatment_preferences FOR UPDATE TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can update own vo2max data" ON public.oura_vo2max FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update own workout data" ON public.oura_workout FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update their own Fitbit tokens" ON public.fitbit_tokens FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own Fitbit tokens" ON public.wearable_tokens FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own alert history" ON public.alert_history FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own alert settings" ON public.alert_settings FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own anomalies" ON public.health_anomalies FOR UPDATE TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can update their own baselines" ON public.user_baselines FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own context" ON public.user_context_enhanced FOR UPDATE TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can update their own dismissals" ON public.risk_alert_dismissals FOR UPDATE USING ((auth.uid() = user_id));
CREATE POLICY "Users can update their own injury history" ON public.user_injuries FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own interests" ON public.user_interests FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own layout preferences" ON public.profiles FOR UPDATE USING ((auth.uid() = id)) WITH CHECK ((auth.uid() = id));
CREATE POLICY "Users can update their own lifestyle" ON public.user_lifestyle FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own medical background" ON public.user_medical FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own memory entries" ON public.yves_memory_bank FOR UPDATE USING ((auth.uid() = user_id));
CREATE POLICY "Users can update their own mindset data" ON public.user_mindset FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own nutrition" ON public.user_nutrition FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE TO authenticated USING ((auth.uid() = id));
CREATE POLICY "Users can update their own profile" ON public.user_profile FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own recommendation feedback" ON public.yves_recommendations FOR UPDATE USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own recovery data" ON public.user_recovery FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own reviews" ON public.provider_reviews FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own sessions" ON public.medical_finder_sessions FOR UPDATE USING ((auth.uid() = user_id));
CREATE POLICY "Users can update their own signals" ON public.onboarding_signals FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own training preferences" ON public.user_training FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update their own triage results" ON public.triage_results FOR UPDATE USING ((auth.uid() = user_id));
CREATE POLICY "Users can update their own wearable sessions" ON public.wearable_sessions FOR UPDATE USING ((auth.uid() = user_id));
CREATE POLICY "Users can update their own wearable summary" ON public.wearable_summary FOR UPDATE USING ((auth.uid() = user_id));
CREATE POLICY "Users can update their own wellness goals" ON public.user_wellness_goals FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can view feedback for their treatment plans" ON public.treatment_plan_feedback FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view function logs" ON public.function_execution_log FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can view helpful votes" ON public.review_helpful_votes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can view notifications" ON public.notification_log FOR SELECT TO authenticated USING ((auth.uid() IS NOT NULL));
CREATE POLICY "Users can view own activity data" ON public.oura_activity FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view own calendar events" ON public.google_calendar_events FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own calendar tokens" ON public.google_calendar_tokens FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own cardiovascular age data" ON public.oura_cardiovascular_age FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view own challenges" ON public.accountability_challenges FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own challenges" ON public.user_challenges FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own context" ON public.user_context FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own injury profiles" ON public.user_injury_profiles FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own insights" ON public.insight_history FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own profile" ON public.user_profiles FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own readiness data" ON public.oura_readiness FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view own reflections" ON public.weekly_reflections FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own resilience data" ON public.oura_resilience FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view own rest mode data" ON public.oura_rest_mode FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view own ring config" ON public.oura_ring_config FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view own shown patterns" ON public.user_shown_patterns FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own sleep data" ON public.oura_sleep FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view own spo2 data" ON public.oura_spo2 FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view own stress data" ON public.oura_stress FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view own sync logs" ON public.google_calendar_sync_logs FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own treatment plans" ON public.treatment_plans FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own treatment preferences" ON public.user_treatment_preferences FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own vo2max data" ON public.oura_vo2max FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view own workout data" ON public.oura_workout FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view services for their treatment plans" ON public.treatment_plan_services FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM public.treatment_plans
  WHERE ((treatment_plans.id = treatment_plan_services.treatment_plan_id) AND (treatment_plans.user_id = auth.uid())))));
CREATE POLICY "Users can view their bookings" ON public."Bookings" FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own Fitbit data" ON public.fitbit_auto_data FOR SELECT TO authenticated USING ((user_id = (auth.uid())::text));
CREATE POLICY "Users can view their own Fitbit data" ON public.wearable_auto_data FOR SELECT TO authenticated USING ((user_id = (auth.uid())::text));
CREATE POLICY "Users can view their own Fitbit tokens" ON public.fitbit_tokens FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own Fitbit tokens" ON public.wearable_tokens FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own Fitbit trends" ON public.fitbit_trends FOR SELECT TO authenticated USING ((user_id = (auth.uid())::text));
CREATE POLICY "Users can view their own activity trends" ON public.activity_trends FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own adaptation profile" ON public.user_adaptation_profile FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own alert history" ON public.alert_history FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own alert settings" ON public.alert_settings FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own anomalies" ON public.health_anomalies FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own baselines" ON public.baseline_profiles FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own briefings" ON public.daily_briefings FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own context" ON public.user_context_enhanced FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own daily trends" ON public.health_trends_daily FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own data maturity" ON public.user_data_maturity FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own deviations" ON public.user_deviations FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own dismissals" ON public.risk_alert_dismissals FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own document versions" ON public.document_versions FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own documents" ON public.user_documents FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own engagement events" ON public.engagement_events FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own escalation logs" ON public.escalation_log FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own feedback" ON public.feedback FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own health profiles" ON public.user_health_profiles FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own injury history" ON public.user_injuries FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own insight actions" ON public.user_insight_actions FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own insight feedback" ON public.insight_feedback FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own insight history" ON public.insight_history FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own insights" ON public.document_insights FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own interests" ON public.user_interests FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own life formulas" ON public.user_life_formula FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own lifestyle" ON public.user_lifestyle FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own medical background" ON public.user_medical FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own memory" ON public.yves_memory_bank FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own memory entries" ON public.yves_memory_bank FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own mindset data" ON public.user_mindset FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own model" ON public.user_model FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own nutrition" ON public.user_nutrition FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own oura logs" ON public.oura_logs FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own oura sync logs" ON public.oura_sync_log FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own plan adherence" ON public.plan_adherence FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own predictions" ON public.prediction_log FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own processing logs" ON public.document_processing_log FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT TO authenticated USING ((auth.uid() = id));
CREATE POLICY "Users can view their own profile" ON public.user_profile FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own prompt history" ON public.prompt_history FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own recommendation outcomes" ON public.recommendation_outcomes FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own recommendations" ON public.adaptive_recommendations FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own recovery data" ON public.user_recovery FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own recovery trends" ON public.recovery_trends FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own risk trajectories" ON public.risk_trajectories FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own sessions" ON public.medical_finder_sessions FOR SELECT USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own signals" ON public.onboarding_signals FOR SELECT TO authenticated USING ((auth.uid() = user_id));
CREATE POLICY "Users can view their own sync health" ON public.sync_health_log FOR SELECT TO authenticated USING ((auth.uid() = user_id));
